server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:weddingdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  web:
    cors:
      allowed-origins: '*'
      allowed-methods: GET,POST,PUT,DELETE