server:
  port: 8080

spring:
  application:
    name: wedding-backend
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  web:
    cors:
      allowed-origins: https://wedding-app-frontend.vercel.app,http://localhost:3000
      allowed-methods: GET,POST,PUT,DELETE

# Wedding API properties
wedding:
  api:
    title: Wedding Application API
    description: API documentation for Wedding Management Application
    version: 1.0
    contact:
      name: Casey Quinn
      email: caseythecoder90@gmail.com
    server:
      url: /
      description: Default Server URL

# Swagger UI / SpringDoc properties
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json