services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: casquinn
      POSTGRES_PASSWORD: bebopYasmim2025!
      POSTGRES_DB: wedding-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
